language: cpp

matrix:
  include:
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: require
  - name: "Windows"
    os: windows
  - name: "MacOS"
    os: osx

install:
  - if [[ "$TRAVIS_JOB_NAME" == "Linux" ]]; sudo apt install qtbase5-dev libqt5svg5-dev qttools5-dev ; fi
  - if [[ "$TRAVIS_JOB_NAME" == "Linux" ]]; sudo apt install zlib1g-dev ; fi

script:
  - git fetch --unshallow # restore repository depth to properly count commits in auto versioning
  - git checkout master   # re-attach to master to satisfy auto versioning
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_JOB_NAME" == "Linux" ]]; then cmake .. -DCMAKE_INSTALL_PREFIX=/usr ; fi
