language: cpp

matrix:
  include:
  #####################
  #
  # Linux build
  #
  #####################
  - name: "Linux"
    os: linux
    dist: bionic
    sudo: require
    
    install:
      - sudo apt-get -y install qtbase5-dev libqt5svg5-dev qttools5-dev
      - sudo apt-get -y install xvfb
      - sudo apt-get -y install pkgconf libqrencode-dev
      - sudo apt-get -y install barcode

    script:
      - git fetch --unshallow # restore repository depth to properly count commits in auto versioning
      - git checkout master   # re-attach to master to satisfy auto versioning
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
      - make -j4
      - xvfb-run ctest
      - sudo make DESTDIR=appdir install ; sudo chown -R $USER appdir ; find appdir/

  #####################
  #
  # Windows build
  #
  #####################
  - name: "Windows"
    os: windows

    script:
      - git fetch --unshallow # restore repository depth to properly count commits in auto versioning
      - git checkout master   # re-attach to master to satisfy auto versioning
      - mkdir build
      - cd build
      #- cmake .. -G "Visual Studio 15 2017 Win64"
      #- cmake --build . --config Release
      #- ctest -C Release
      #- cpack -C Release -G NSIS64

  #####################
  #
  # MacOS build
  #
  #####################
  - name: "MacOS"
    os: osx

    install:
      - brew install qt

    script:
      - git fetch --unshallow # restore repository depth to properly count commits in auto versioning
      - git checkout master   # re-attach to master to satisfy auto versioning
      - mkdir build
      - cd build
      - cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt
      - make -j4
      - ctest --verbose
