name: CI Snapshots

on:
  push:
    branches:
      - master

jobs:
  ubuntu-build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install qtbase5-dev libqt5svg5-dev qttools5-dev
        sudo apt-get -y install xvfb
        sudo apt-get -y install pkgconf libqrencode-dev
        sudo apt-get -y install barcode

#    - name: unshallow
#      run: |
#        git checkout master

    - name: cmake configure
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr
        VERSION=$(cat VERSION)

    - name: build
      run: |
        cd build
        make -j4

    - name: test
      run: |
        cd build
        xvfb-run ctest

    - name: create AppImage
      run: |
        cd build
        # Download AppImage QT deployment tool (local snapshot -- original at github/probono)
        wget -c "https://github.com/jimevins/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
        chmod a+x linuxdeployqt*.AppImage
        #
        # Create AppImage
        #
        make DESTDIR=appdir install
        unset QTDIR; unset QT_PLUGIN_PATH
        ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -qmake=${QMAKE_PATH} -bundle-non-qt-libs
        ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -qmake=${QMAKE_PATH} -appimage
        mv ./gLabels*.AppImage glabels-${VERSION}-x86_64.AppImage
      